// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: test/proto/echo.proto

package echo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_test_proto_echo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_echo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_test_proto_echo_proto_rawDescGZIP(), []int{0}
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_test_proto_echo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_echo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_test_proto_echo_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

var File_test_proto_echo_proto protoreflect.FileDescriptor

const file_test_proto_echo_proto_rawDesc = "" +
	"\n" +
	"\x15test/proto/echo.proto\x12\x04echo\"\t\n" +
	"\aRequest\"\x1a\n" +
	"\bResponse\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip24\n" +
	"\x04Echo\x12,\n" +
	"\vGetServerIP\x12\r.echo.Request\x1a\x0e.echo.ResponseB\x12Z\x10proto/proto;echob\x06proto3"

var (
	file_test_proto_echo_proto_rawDescOnce sync.Once
	file_test_proto_echo_proto_rawDescData []byte
)

func file_test_proto_echo_proto_rawDescGZIP() []byte {
	file_test_proto_echo_proto_rawDescOnce.Do(func() {
		file_test_proto_echo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_test_proto_echo_proto_rawDesc), len(file_test_proto_echo_proto_rawDesc)))
	})
	return file_test_proto_echo_proto_rawDescData
}

var file_test_proto_echo_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_test_proto_echo_proto_goTypes = []any{
	(*Request)(nil),  // 0: echo.Request
	(*Response)(nil), // 1: echo.Response
}
var file_test_proto_echo_proto_depIdxs = []int32{
	0, // 0: echo.Echo.GetServerIP:input_type -> echo.Request
	1, // 1: echo.Echo.GetServerIP:output_type -> echo.Response
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_test_proto_echo_proto_init() }
func file_test_proto_echo_proto_init() {
	if File_test_proto_echo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_test_proto_echo_proto_rawDesc), len(file_test_proto_echo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_test_proto_echo_proto_goTypes,
		DependencyIndexes: file_test_proto_echo_proto_depIdxs,
		MessageInfos:      file_test_proto_echo_proto_msgTypes,
	}.Build()
	File_test_proto_echo_proto = out.File
	file_test_proto_echo_proto_goTypes = nil
	file_test_proto_echo_proto_depIdxs = nil
}
